# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "hugo-theme-electrichasgoneaudi"
license = "MIT"
licenselink = "https://github.com/electrichasgoneaudi/hugo-theme-electrichasgoneaudi/blob/master/LICENSE.md"
description = "electrichasgoneaudi theme for Hugo"
homepage = "https://github.com/electrichasgoneaudi/hugo-theme-altinn"
repo = "https://github.com/electrichasgoneaudi/hugo-theme-altinn"
tags = ["documentation", "menu","slide","search"]
features = ["documentation","menu","nested sections","search","slide", "attachments"]
min_version = 0.73

[author]
  name = "electrichasgoneaudi"
  homepage = "https://electrichasgoneaudi.net"

[original]
  name = "Docdock"
  homepage = "https://docdock.netlify.com/"
  repo = "https://github.com/vjeantet/hugo-theme-docdock"
  licenselink = "https://github.com/vjeantet/hugo-theme-docdock/blob/master/LICENSE.md"